CREATE TABLE survivor (
  id bigint generated by default as identity (start with 1) NOT NULL,
	name varchar(255) NOT NULL,
	age tinyint NOT NULL,
	gender varchar(20) NOT NULL,
	infected boolean DEFAULT false NOT NULL,
	CONSTRAINT survivor_pkey PRIMARY KEY (id)
);

CREATE TABLE contamination_log (
  id bigint generated by default as identity (start with 1) NOT NULL,
  reporter_survivor bigint NOT NULL,
  reported_survivor bigint NOT NULL,
  CONSTRAINT contamination_log_pkey PRIMARY KEY (id)
);
ALTER TABLE contamination_log ADD FOREIGN KEY (reporter_survivor) REFERENCES survivor(id);
ALTER TABLE contamination_log ADD FOREIGN KEY (reported_survivor) REFERENCES survivor(id);

CREATE TABLE inventory (
  id bigint generated by default as identity (start with 1) NOT NULL,
  resource VARCHAR(20) NOT NULL,
  quantity tinyint NOT NULL,
  survivor bigint NOT NULL,
  CONSTRAINT inventory_pkey PRIMARY KEY (id)
);
ALTER TABLE inventory ADD FOREIGN KEY (survivor) REFERENCES survivor(id);